#!/bin/sh

#--------------------------------------
# Author: Yusuf Abdulsttar
#--------------------------------------

set -e

case "$1" in
    start)
        echo "Loadling scull"
        start-stop-daemon -S -n scull
        ;;
    stop)
        echo "Unloading scull"
        start-stop-daemon -K -n scull
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac
exit 0
